[package]
name = "indexing_v1"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = "0.15.2"
id = { version = "0.1.0", path = "../id" }
indexmap = "2.7.0"
insta = "1.42.0"
itertools = "0.14.0"
la-arena = "0.3.1"
petgraph = "0.7.0"
rowan = "0.16.1"
rustc-hash = "2.1.0"
smol_str = "0.3.2"
syntax = { version = "0.1.0", path = "../syntax" }

[dev-dependencies]
lexing = { path = "../lexing" }
parsing = { path = "../parsing" }
