[package]
name = "compat"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.2"
lexing = { version = "0.1.0", path = "../crates/lexing" }
parsing = { version = "0.1.0", path = "../crates/parsing" }
