[package]
name = "lowering_v1"
version = "0.1.0"
edition = "2021"

[dependencies]
id = { version = "0.1.0", path = "../id" }
indexing_v1 = { version = "0.1.0", path = "../indexing_v1" }
indexmap = "2.7.1"
insta = "1.42.1"
lexing = { version = "0.1.0", path = "../lexing" }
parsing = { version = "0.1.0", path = "../parsing" }
rowan = "0.16.1"
rustc-hash = "2.1.0"
smol_str = "0.3.2"
syntax = { version = "0.1.0", path = "../syntax" }
test_each_file = "0.3.4"
