[package]
name = "tests-integration"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
building = { version = "0.1.0", path = "../crates/building" }
files = { version = "0.1.0", path = "../crates/files" }
glob = "0.3.2"
indexing = { version = "0.1.0", path = "../crates/indexing" }
lexing = { version = "0.1.0", path = "../crates/lexing" }
lowering = { version = "0.1.0", path = "../crates/lowering" }
parsing = { version = "0.1.0", path = "../crates/parsing" }
resolving = { version = "0.1.0", path = "../crates/resolving" }
smol_str = "0.3.2"
syntax = { version = "0.1.0", path = "../crates/syntax" }

[build-dependencies]
convert_case = "0.8.0"
itertools = "0.14.0"

[dev-dependencies]
insta = "1.43.1"
