[package]
name = "tests-package-set"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3.2"
lexing = { version = "0.1.0", path = "../crates/lexing" }
parsing = { version = "0.1.0", path = "../crates/parsing" }
